---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metadata-api
  labels:
    app: metadata-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gunicorn
  template:
    metadata:
      labels:
        app: nginx-gunicorn
    spec:
      containers:
        - name: nginx-gunicorn
          image: pydevswarmregistry.azurecr.io/python-gunicorn-nginx:latest
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: metadata-api
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  labels:
    app: metadata-api
spec:
  type: LoadBalancer
  ports:
    - name: "http"
      port: 80
      targetPort: 80
      protocol: "TCP"
  selector:
    app: metadata-api
