---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: metadata-api
  labels:
    app: metadata-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-gunicorn
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: nginx-gunicorn
    spec:
      containers:
        - name: nginx-gunicorn
          #replace with GCP Project ID and path to application container
          image: gcr.io/[PROJECT-ID]/python-gunicorn-nginx:latest
          ports:
            - name: http
              containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: metadata-api
  labels:
    app: metadata-api
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    app: nginx-gunicorn

---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/secure-backends: "false"
    nginx.ingress.kubernetes.io/whitelist-source-range: 0.0.0.0/0
  name: services-ingress
spec:
  rules:
    - http:
        paths:
          - path: /metadata/
            backend:
              serviceName: metadata-api
              servicePort: http
